### ISSUE TITLE
GitLab CI integration does not work as stated in README.md

### ISSUE THREAD

**Issue by mabuchner** [Witekio/clang-format-checker-docker#3]
Doing the GitLab CI integration as stated in README.md does not work.

This

```yml
check-format:
  image: witekio/clang-format-checker
  script:
    - run-clang-format.py -r src
```

will result in the following error

```
usage: run-clang-format.py [-h] [--clang-format-executable EXECUTABLE]
                           [--extensions EXTENSIONS] [-r] [-q] [-j N]
                           [--color {auto,always,never}] [-e PATTERN]
                           file [file ...]
run-clang-format.py: error: unrecognized arguments: -c if [ -x /usr/local/bin/bash ]; then
  exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
  exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
  exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
  exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
  exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
  exec /bin/sh 
elif [ -x /busybox/sh ]; then
  exec /busybox/sh 
else
  echo shell not found
  exit 1
fi
```

**Comment by mabuchner** [comment]
I could solve the problem by manually resetting the `entrypoint` of the image

```yml
check-format:
  image:
    name: witekio/clang-format-checker
    entrypoint: [""]
  script:
    - run-clang-format.py -r src
```
